server:
  port: 8000

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  server:
    # 是否开启自我保护机制
    enable-self-preservation: true
    # 续约成功的阈值，当续约成功百分比低于85%，此时会自动开启自我保护机制
    renewal-percent-threshold: 0.85
    # 期望eureka客户端续约的时间间隔
    expected-client-renewal-interval-seconds: 30
    # 对于不可用服务间隔多久将其剔除，默认是0s，即：立即剔除
    eviction-interval-timer-in-ms: 2000
  # 注册自己到注册中心
  client:
    # 向 Eureka 注册中心注册自己
    register-with-eureka: true
    # fetch-registry如果为false,则表示自己为注册中心,客户端的化为 ture
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

# 访问地址： http://localhost:8000/


