spring:
  application:
    name: mynotebook-user

  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 8
        min-idle: 0

eureka:
  client:
    register-with-eureka: true   #注册到eureka
    fetch-registry: true    # 获取注册信息
    # 需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8761/eureka
      registry-fetch-interval-seconds: 3 #3秒钟去eureka拿一次微服务注册实例，默认值 30
