#spring:
#  application:
#    name: mynotebook-book

#eureka:
#  client:
#    register-with-eureka: true   #注册到eureka
#    fetch-registry: true    # 获取注册信息
#    # 需要指向Eureka服务端地址，这样才能进行注册
#    service-url:
#      defaultZone: http://localhost:8000/eureka
#      registry-fetch-interval-seconds: 3 #3秒钟去eureka拿一次微服务注册实例，默认值 30